/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "i18n": {
        "metadata": {
            "bot_name": string;
            "description": string;
            "short_description": string;
        };
        "command_descriptions": {
            "start": string;
            "hello": string;
        };
        "shared": {
            "buttons": {
                "close": string;
            };
        };
        "command": {
            "start": {
                "message": string;
                "buttons": {
                    "welcome_button": string;
                };
            };
            "help": {
                "message": string;
            };
            "hello": {
                "message": string;
                "scene": {
                    "first_message": string;
                    "second_message": string;
                };
            };
            "helloPrivate": {
                "message": string;
            };
            "helloGroup": {
                "message": string;
            };
        };
        "menus": {
            "start": {
                "message": string;
                "buttons": {
                    "welcome_button": string;
                    "close": string;
                };
            };
            "hello": {
                "message": string;
                "scene": {
                    "first_message": string;
                };
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
