export enum BOT_COMMANDS {
  START = 'start',
  HELLO = 'hello',
  QUIZ = 'quiz',
  HELLO_PRIVATE = 'hello_private',
  HELLO_GROUP = 'hello_group',
  HELLO_RESTRICTED = 'hello_restricted',
  QUIZ_MANAGER = 'quiz_manager',
}

export const TELEGRAM_BTN_ACTIONS = {
  CLOSE: 'id_0_close',
  QUIZ_ADMIN_CREATE: 'id_1_quiz_create',
  QUIZ_ADMIN_UPDATE: 'id_2_quiz_update',
  QUIZ_ADMIN_CREATE_EXAMPLE: 'id_3_quiz_create_example',
  LEAVE: 'id_4_leave',
  PREVIEW_QUIZ: 'id_5_preview_quiz',
  SAVE_QUIZ: 'id_6_save',
};

export const SCENES = {
  SCENE_HELLO: 'scene_hello',
  SCENE_QUIZ: 'scene_quiz',
  SCENE_QUIZ_MANAGER: 'scene_quiz_manager',
};

export enum BOT_ON {
  POLL_ANSWER = "poll_answer",
  TEXT = "text",
  MESSAGE = "message",
  CALLBACK_QUERY = "callback_query",
  CHANNEL_POST = "channel_post",
  CHAT_MEMBER = "chat_member",
  CHOSEN_INLINE_RESULT = "chosen_inline_result",
  EDITED_CHANNEL_POST = "edited_channel_post",
  MESSAGE_REACTION = "message_reaction",
  MESSAGE_REACTION_COUNT = "message_reaction_count",
  EDITED_MESSAGE = "edited_message",
  INLINE_QUERY = "inline_query",
  MY_CHAT_MEMBER = "my_chat_member",
  PRE_CHECKOUT_QUERY = "pre_checkout_query",
  POLL = "poll",
  SHIPPING_QUERY = "shipping_query",
  CHAT_JOIN_REQUEST = "chat_join_request",
  CHAT_BOOST = "chat_boost",
  REMOVED_CHAT_BOOST = "removed_chat_boost",
  FORWARD_DATE = "forward_date",
  NEW_CHAT_MEMBERS = "new_chat_members",
  LEFT_CHAT_MEMBER = "left_chat_member",
  NEW_CHAT_TITLE = "new_chat_title",
  NEW_CHAT_PHOTO = "new_chat_photo",
  DELETE_CHAT_PHOTO = "delete_chat_photo",
  GROUP_CHAT_CREATED = "group_chat_created",
  SUPERGROUP_CHAT_CREATED = "supergroup_chat_created",
  CHANNEL_CHAT_CREATED = "channel_chat_created",
  MESSAGE_AUTO_DELETE_TIMER_CHANGED = "message_auto_delete_timer_changed",
  MIGRATE_TO_CHAT_ID = "migrate_to_chat_id",
  MIGRATE_FROM_CHAT_ID = "migrate_from_chat_id",
  PINNED_MESSAGE = "pinned_message",
  INVOICE = "invoice",
  SUCCESSFUL_PAYMENT = "successful_payment",
  USERS_SHARED = "users_shared",
  CHAT_SHARED = "chat_shared",
  CONNECTED_WEBSITE = "connected_website",
  WRITE_ACCESS_ALLOWED = "write_access_allowed",
  PASSPORT_DATA = "passport_data",
  PROXIMITY_ALERT_TRIGGERED = "proximity_alert_triggered",
  BOOST_ADDED = "boost_added",
  FORUM_TOPIC_CREATED = "forum_topic_created",
  FORUM_TOPIC_EDITED = "forum_topic_edited",
  FORUM_TOPIC_CLOSED = "forum_topic_closed",
  FORUM_TOPIC_REOPENED = "forum_topic_reopened",
  GENERAL_FORUM_TOPIC_HIDDEN = "general_forum_topic_hidden",
  GENERAL_FORUM_TOPIC_UNHIDDEN = "general_forum_topic_unhidden",
  GIVEAWAY_CREATED = "giveaway_created",
  GIVEAWAY = "giveaway",
  GIVEAWAY_WINNERS = "giveaway_winners",
  GIVEAWAY_COMPLETED = "giveaway_completed",
  VIDEO_CHAT_SCHEDULED = "video_chat_scheduled",
  VIDEO_CHAT_STARTED = "video_chat_started",
  VIDEO_CHAT_ENDED = "video_chat_ended",
  VIDEO_CHAT_PARTICIPANTS_INVITED = "video_chat_participants_invited",
  WEB_APP_DATA = "web_app_data",
  ANIMATION = "animation",
  DOCUMENT = "document",
  HAS_MEDIA_SPOILER = "has_media_spoiler",
  AUDIO = "audio",
  CONTACT = "contact",
  DICE = "dice",
  GAME = "game",
  LOCATION = "location",
  PHOTO = "photo",
  STICKER = "sticker",
  STORY = "story",
  VENUE = "venue",
  VIDEO = "video",
  VIDEO_NOTE = "video_note",
  VOICE = "voice",
}
